[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "account-abstraction/=lib/account-abstraction/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "foundry-era-contracts/=lib/foundry-era-contracts/",
]
is-system = true
via-ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
